// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  edit_wrapper: string;
  page_title: string;
  'text-link': string;
}
declare const cssExports: CssExports;
export default cssExports;
