// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  avatar: string;
  avatar_overlay: string;
  banner_overlay: string;
  btn_edit_banner: string;
  edit_wrapper: string;
  forms: string;
  image_banner: string;
  image_header: string;
  page_title: string;
  'text-link': string;
}
declare const cssExports: CssExports;
export default cssExports;
