// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  page_title: string;
  'text-link': string;
}
declare const cssExports: CssExports;
export default cssExports;
