// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  button_form: string;
  button_register_link: string;
  form: string;
  login: string;
  login_description: string;
  login_title: string;
  login_wrapper: string;
}
declare const cssExports: CssExports;
export default cssExports;
