// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  close_btn: string;
  header: string;
  header_title: string;
  image_cropper: string;
  'modal-fade': string;
  'modal-slide-dow': string;
  'modal-slide-down': string;
  'modal-slide-up': string;
  'modal-zoom': string;
  modal_body: string;
  modal_content: string;
  overlay: string;
}
declare const cssExports: CssExports;
export default cssExports;
