// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fb-checkbox-button': string;
  'fb-checkbox-description': string;
  'fb-checkbox-error': string;
  'fb-checkbox-field': string;
  'fb-checkbox-icon': string;
  'fb-checkbox-label': string;
  'fb-checkbox-text-container': string;
}
declare const cssExports: CssExports;
export default cssExports;
