// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  input: string;
  link: string;
  support_hellpers: string;
  support_hellpers_title: string;
  title: string;
  wrapper: string;
}
declare const cssExports: CssExports;
export default cssExports;
