// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'aspect-square': string;
  border: string;
  container: string;
  flex: string;
  'flex-col': string;
  'flex-shrink': string;
  'gap-3': string;
  image_cropper: string;
  'items-center': string;
  'modal-fade': string;
  'modal-zoom': string;
  modal_content: string;
  'object-contain': string;
  'object-cover': string;
  overlay: string;
  static: string;
  transform: string;
  'w-full': string;
}
declare const cssExports: CssExports;
export default cssExports;
