// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'color-danger': string;
  'color-default': string;
  'color-success': string;
  'color-warning': string;
  description: string;
  errorfield: string;
  floatingLabel: string;
  icon: string;
  inputContainer: string;
  item: string;
  listBox: string;
  popover: string;
  'radius-full': string;
  'radius-lg': string;
  'radius-md': string;
  'radius-none': string;
  'radius-sm': string;
  'radius-xl': string;
  'size-lg': string;
  'size-md': string;
  'size-sm': string;
  'size-xs': string;
  trigger: string;
  value: string;
  wrapper: string;
}
declare const cssExports: CssExports;
export default cssExports;
