// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'radius-full': string;
  'radius-lg': string;
  'radius-md': string;
  'radius-none': string;
  'radius-sm': string;
  'radius-xl': string;
  'size-lg': string;
  'size-md': string;
  'size-sm': string;
  'size-xs': string;
  'type-default': string;
  'type-icon': string;
  'variant-dark': string;
  'variant-error': string;
  'variant-ghost': string;
  'variant-ghost-green': string;
  'variant-ghost-purple': string;
  'variant-ghost-red': string;
  'variant-indigo': string;
  'variant-orange': string;
  'variant-primary': string;
  'variant-purple': string;
  'variant-soft-blue': string;
  'variant-soft-green': string;
  'variant-soft-orange': string;
  'variant-soft-purple': string;
  'variant-soft-red': string;
  'variant-success': string;
  'variant-teal': string;
  'variant-warning': string;
  wrapper: string;
}
declare const cssExports: CssExports;
export default cssExports;
