// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  characterCounter: string;
  clearButton: string;
  'color-danger': string;
  'color-default': string;
  'color-success': string;
  'color-warning': string;
  errorfield: string;
  icon: string;
  inputContainer: string;
  inputElement: string;
  inputWrapper: string;
  label: string;
  prefix: string;
  'radius-full': string;
  'radius-lg': string;
  'radius-md': string;
  'radius-none': string;
  'radius-sm': string;
  'radius-xl': string;
  'size-lg': string;
  'size-md': string;
  'size-sm': string;
  'size-xs': string;
  suffix: string;
  textareaClearButton: string;
  textareaContainer: string;
  textareaCounter: string;
  textareaElement: string;
  wrapper: string;
}
declare const cssExports: CssExports;
export default cssExports;
