// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  spin: string;
  spinner: string;
}
declare const cssExports: CssExports;
export default cssExports;
