// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  menu_content: string;
  menu_group: string;
  menu_header: string;
  menu_label: string;
}
declare const cssExports: CssExports;
export default cssExports;
