// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  active: string;
  badge: string;
  menu_content: string;
  menu_item: string;
  menu_name: string;
}
declare const cssExports: CssExports;
export default cssExports;
