// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  avatar: string;
  footer: string;
  footer_role: string;
  footer_user: string;
  footer_user_name: string;
  main: string;
  nav: string;
  wrapper: string;
}
declare const cssExports: CssExports;
export default cssExports;
