// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'google-icon': string;
  googleIcon: string;
  wrapper: string;
}
declare const cssExports: CssExports;
export default cssExports;
