// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fb-switch-button': string;
  'fb-switch-description': string;
  'fb-switch-error': string;
  'fb-switch-field': string;
  'fb-switch-label': string;
  'fb-switch-text-container': string;
  'fb-switch-thumb': string;
}
declare const cssExports: CssExports;
export default cssExports;
