// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'color-danger': string;
  'color-default': string;
  'color-success': string;
  'color-warning': string;
  colorDanger: string;
  colorDefault: string;
  colorSuccess: string;
  colorWarning: string;
  floatingLabel: string;
  icon: string;
  inputContainer: string;
  inputElement: string;
  inputWrapper: string;
  'radius-full': string;
  'radius-lg': string;
  'radius-md': string;
  'radius-none': string;
  'radius-sm': string;
  'radius-xl': string;
  radiusFull: string;
  radiusLg: string;
  radiusMd: string;
  radiusNone: string;
  radiusSm: string;
  radiusXl: string;
  'size-lg': string;
  'size-md': string;
  'size-sm': string;
  'size-xs': string;
  sizeLg: string;
  sizeMd: string;
  sizeSm: string;
  sizeXs: string;
  wrapper: string;
}
declare const cssExports: CssExports;
export default cssExports;
