// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'toast-action': string;
  'toast-base': string;
  'toast-close': string;
  'toast-description': string;
  'toast-error': string;
  'toast-info': string;
  'toast-loading': string;
  'toast-success': string;
  'toast-title': string;
  'toast-warning': string;
}
declare const cssExports: CssExports;
export default cssExports;
